language: java
jdk:
  - openjdk15

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - stas.korobeinikov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
#TODO:    - CODECOV_TOKEN='abc34d4e-2ceb-4db8-b92f-c4ba53dab9c2'